services:
  - type: web
    name: pai6-final
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm ci && npm run build
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 18.20.3
      - key: UPLOAD_DIR
        value: uploads